# tap
tap "homebrew/cask-fonts"

# formulae
brew "awscli"
brew "bash"
brew "bloaty"
brew "ffmpeg"
brew "git-extras"
brew "git-lfs"
brew "gradle"
brew "jq"
brew "kdoctor"
brew "mint"
brew "openjdk"
brew "rbenv"
brew "swagger-codegen"
brew "tree"

# cask
cask "adobe-creative-cloud"
cask "android-studio"
cask "appcleaner"
cask "arc"
cask "brooklyn"
cask "charles"
cask "cheatsheet"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "deepl"
cask "discord"
cask "drawio"
cask "figma"
cask "firefox"
cask "font-jetbrains-mono"
cask "fork"
cask "google-chrome"
cask "iina"
cask "itsycal"
cask "jasper"
cask "karabiner-elements"
cask "miro"
cask "mp3tag"
cask "notion"
cask "obs"
cask "onyx"
cask "raycast"
cask "sf-symbols"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
cask "warp"
cask "webex"
cask "xcodes"
cask "zoom"

# Mac App Store
mas "Amazon Prime Video", id: 545519333
mas "RunCat", id: 1429033973
mas "Spark", id: 1176895641